### ISSUE TITLE
Cordova-Plugin-DocumentReader API is not npm registry

### ISSUE THREAD

**Issue by raoghuge** [regulaforensics/Cordova-Plugin-DocumentReader-Sample#1]
Hi Team,
I was working on building an ionic app on top of your plugins, however, I have came across following error while installing API plugin.

![image](https://user-images.githubusercontent.com/2690456/65612456-2792c100-df69-11e9-84a5-39944443d9a2.png)

**Comment by vyakimchik** [comment]
Hello,

Unfortunately, this package hasn't been released yet. We're working on it. The manual on how to build the demo application and how to add a new SDK to your project will be updated as soon as we complete all tasks. You can type your email and I'll notify you as soon as it's live.
